import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" data-oid="b1jifow">
      <head data-oid="x0ail_k"></head>
      <body className="antialiased" data-oid="hqec2:a">
        {children}

        <Script
          src="/onlook-preload-script.js"
          strategy="beforeInteractive"
          type="module"
          id="onlook-preload-script.js"
          data-oid=":kbir4j">
        </Script>
      </body>
    </html>);

}